import type { GameMode } from "./types";

export interface BookPage {
  id: string;
  title: string;
  icon: string;
  what: string;
  reality: string;
  inGame: string;
  example: string;
  /** When set, a shortcut button closes the book and switches to this mode. */
  practiceMode?: GameMode;
}

export interface BookCategory {
  id: string;
  title: string;
  icon: string;
  pages: BookPage[];
}

export const BOOK_CATEGORIES: BookCategory[] = [
  {
    id: "basics",
    title: "ネットワーク基礎",
    icon: "📘",
    pages: [
      {
        id: "network",
        title: "ネットワークとは",
        icon: "🌐",
        what: "複数のコンピューターや機器が、データをやり取りできるようにつながった仕組みのこと。",
        reality: "会社のPCやプリンター、スマホなどが、ケーブルやWi-Fiでお互いに情報をやり取りしている。",
        inGame: "このゲームでは、PC・スイッチ・ルーターなどを配線し、設定することでネットワークを作る。",
        example: "PC ── Switch ── Router ── Internet",
      },
      {
        id: "lan",
        title: "LANとは",
        icon: "🏢",
        what: "Local Area Networkの略。会社やオフィスなど、限られた範囲内のネットワークのこと。",
        reality: "1つのオフィス内のPC・プリンター・サーバーなどをつなぐ社内ネットワークがLAN。",
        inGame: "ルーターより内側（LANポート側）に接続された機器同士のネットワークがLAN。",
        example: "Router\n  └ Switch\n     ├ PC\n     └ PC",
      },
      {
        id: "wan",
        title: "WANとは",
        icon: "🛰️",
        what: "Wide Area Networkの略。LANの外側、インターネットを含む広い範囲のネットワークのこと。",
        reality: "本社と支店をつなぐ回線や、インターネットそのものがWANにあたる。",
        inGame: "ルーターのWANポートから先（ONU・インターネット側）がWAN。",
        example: "Router [WANポート] ── ONU ── Internet",
      },
      {
        id: "internet",
        title: "インターネットとは",
        icon: "☁️",
        what: "世界中のネットワークが相互につながった、最も大きなネットワークのこと。",
        reality: "ISP（インターネットサービスプロバイダ）の回線を通じて世界中とつながる。",
        inGame: "画面上の☁️ INTERNETは、ISPの回線の出口を表す固定の機器として扱う。",
        example: "Internet ── ONU ── Router",
      },
    ],
  },
  {
    id: "devices",
    title: "機器",
    icon: "🖥️",
    pages: [
      {
        id: "onu",
        title: "ONU（回線終端装置）",
        icon: "📶",
        what: "ISPの光回線などを、ルーターがつなげられる信号に変換する機器。",
        reality: "光回線を家やオフィスに引き込んだ末端に設置され、ルーターのWANポートにつなぐ。",
        inGame: "☁️ INTERNETとルーターの間に必ず設置する。ONUなしではインターネットに出られない。",
        example: "Internet ── ONU ── Router[WAN]",
        practiceMode: "connecting",
      },
      {
        id: "router",
        title: "ルーター",
        icon: "🌐",
        what: "LANとWANをつなぎ、複数の機器でインターネット回線を共有できるようにする機器。",
        reality: "DHCPで社内のPCにIPアドレスを自動的に配り、NATでインターネットへの出入り口になる。",
        inGame: "⚙設定でLAN側のIPアドレス・DHCPの範囲・NATのON/OFFを設定できる。",
        example: "Internet ── ONU ── Router ── Switch ── PC",
        practiceMode: "settings",
      },
      {
        id: "switch",
        title: "スイッチ",
        icon: "🔀",
        what: "複数のネットワーク機器を接続し、LANの中でデータを中継する装置。",
        reality: "PCやプリンターなどをまとめて接続し、ポート数を超えて増やしたいときに追加する。",
        inGame: "PCが増えてルーターのポートだけでは足りなくなった場合などに使用する。ポート数には上限がある。",
        example: "Router\n  └ Switch\n     ├ PC\n     ├ PC\n     └ PC",
        practiceMode: "connecting",
      },
      {
        id: "wifi",
        title: "Wi-Fiアクセスポイント",
        icon: "📡",
        what: "有線LANの電波を無線化し、PCやスマホをケーブルなしでつなげるようにする機器。",
        reality: "会議室やフリーアドレス席など、配線しにくい場所への接続手段として使われる。",
        inGame: "スイッチやルーターに有線で接続し、無線ポートに複数台の機器を同時接続できる。",
        example: "Switch ── AP ))) PC / スマホ",
      },
      {
        id: "server",
        title: "サーバー",
        icon: "🖥️",
        what: "社内のPCなどに何らかのサービス（データ共有など）を提供するコンピューター。",
        reality: "ファイルサーバー・メールサーバーなど、常時稼働しアクセスされることが多い。",
        inGame: "固定IPで設置することが多い。他のPCと同じ手順で配線・設定する。",
        example: "Switch ── Server（固定IP）",
        practiceMode: "settings",
      },
      {
        id: "desktop_pc",
        title: "デスクトップPC",
        icon: "🖥️",
        what: "社員が使う据え置き型の端末。",
        reality: "オフィスの机に固定で置かれ、有線LANケーブルでネットワークに接続することが多い。",
        inGame: "有線LANポートのみを持つ。DHCPで自動取得するか、手動でIPアドレスを設定する。",
        example: "デスクトップPC → Switch → Router → Internet",
      },
      {
        id: "notebook_pc",
        title: "ノートPC",
        icon: "💻",
        what: "バッテリーを内蔵し、持ち運んで使える端末。",
        reality: "会議室や外出先など、配線しにくい場所ではWi-Fiで接続することが多い。",
        inGame: "Wi-Fiポートのみを持ち、有線では接続できない。Wi-Fiアクセスポイント経由で接続する。",
        example: "ノートPC ))) AP ── Switch ── Router",
        practiceMode: "connecting",
      },
      {
        id: "workstation",
        title: "ワークステーション",
        icon: "🖲️",
        what: "CADや設計など、重い処理を必要とする作業向けの高性能な端末。",
        reality: "一般的なPCより高価だが、重い処理を必要とする専門部署に導入される。",
        inGame: "有線LANポートのみを持つ。設置・配線・設定の手順は他のPCと同じ。",
        example: "ワークステーション → Switch → Router → Internet",
      },
    ],
  },
  {
    id: "wiring",
    title: "配線",
    icon: "🔌",
    pages: [
      {
        id: "cable",
        title: "LANケーブル",
        icon: "🔌",
        what: "機器同士を物理的につなぎ、電気信号でデータをやり取りするケーブル。",
        reality: "規格（Cat6など）ごとに対応速度や最大長が決まっており、1本あたり最大100m程度が目安。",
        inGame: "配置した機器の座標から実際の距離を計算し、100mを超えると配線できても通信できない扱いになる。",
        example: "PC ──(23.4m)── LAN Jack",
        practiceMode: "connecting",
      },
      {
        id: "lan_jack",
        title: "LANコンセント（LANジャック）",
        icon: "🔌",
        what: "壁に設置する情報コンセント。PCから来たケーブルの終端になる。",
        reality: "壁の中の配線を通じて、離れた通信室のパッチパネルまでつながっている。",
        inGame: "PC側とパッチパネル側、2つのポートを持つ。両方をケーブルでつなぐ必要がある。",
        example: "PC ── LAN Jack ── (壁内配線) ── Patch Panel",
        practiceMode: "connecting",
      },
      {
        id: "patch_panel",
        title: "パッチパネル",
        icon: "🗄️",
        what: "通信室でLANコンセントからの配線をまとめ、スイッチへ引き渡す機器。",
        reality: "どのLANジャックがどのスイッチポートにつながっているか、パッチパネルで管理する。",
        inGame: "PCが増えてルーターのポートだけでは足りなくなった場合などに、スイッチと同じように使う。",
        example: "Router\n   └ Switch\n      └ Patch Panel\n         └ LAN Jack ── PC",
        practiceMode: "connecting",
      },
      {
        id: "rack",
        title: "通信ラック",
        icon: "🗃️",
        what: "通信室に設置し、ONU・ルーター・スイッチ・パッチパネルなどをまとめて収める什器。",
        reality: "機器を棚板やネジで固定し、配線を整理しやすくする。高さは「U」という単位で管理される。",
        inGame: "通信室に置く装飾的な設備で、ケーブルはつなげない。ラックの近くに機器をまとめて配置しよう。",
        example: "通信室\n ├ 🗃️ Rack\n ├ 📶 ONU\n ├ 🌐 Router\n ├ 🔀 Switch\n └ 🗄️ Patch Panel",
      },
    ],
  },
  {
    id: "settings",
    title: "ネットワーク設定",
    icon: "⚙️",
    pages: [
      {
        id: "ip",
        title: "IPアドレス",
        icon: "🔢",
        what: "ネットワーク上の機器を識別するための番号（例：192.168.1.10）。",
        reality: "同じネットワーク内で重複してはいけない。重複すると通信できなくなる。",
        inGame: "DHCPで自動取得するか、⚙設定画面で手動設定できる。重複すると診断で検出される。",
        example: "PC-01: 192.168.1.10\nPC-02: 192.168.1.11",
        practiceMode: "settings",
      },
      {
        id: "subnet",
        title: "サブネットマスク",
        icon: "🧮",
        what: "IPアドレスのうち、どこまでが「ネットワークの範囲」かを表す値（例：255.255.255.0）。",
        reality: "同じサブネットマスクの範囲内にある機器同士は、ルーターを介さず直接通信できる。",
        inGame: "IPアドレスとセットで設定する。ゲートウェイと違うサブネットだと通信できない。",
        example: "IP: 192.168.1.10\nMask: 255.255.255.0",
        practiceMode: "settings",
      },
      {
        id: "dhcp",
        title: "DHCP",
        icon: "🤖",
        what: "PCなどにIPアドレスを自動的に割り当てる仕組み。",
        reality: "ルーターがDHCPサーバーとなり、あらかじめ決めた範囲からIPアドレスを配る。",
        inGame: "ルーターの⚙設定でON/OFF・配布範囲を設定できる。PC側は「自動取得」を選ぶと使える。",
        example: "DHCP範囲：192.168.1.100～200",
        practiceMode: "settings",
      },
      {
        id: "gateway",
        title: "デフォルトゲートウェイ",
        icon: "🚪",
        what: "自分のネットワークの外（インターネットなど）へ出るときの出口となる機器のIPアドレス。",
        reality: "通常はルーターのLAN側IPアドレスを指定する。",
        inGame: "設定が空、または間違っていると、社内通信はできてもインターネットに出られなくなる。",
        example: "PC Gateway = Router LAN IP (192.168.1.1)",
        practiceMode: "settings",
      },
      {
        id: "dns",
        title: "DNS",
        icon: "📇",
        what: "ドメイン名（www.example.comなど）をIPアドレスに変換する仕組み。",
        reality: "DNSが正しく設定されていないと、IPアドレスへの通信はできてもサイト名でのアクセスができない。",
        inGame: "PCの⚙設定でDNSサーバーのIPアドレスを設定する（多くの場合ルーターのIP）。",
        example: "DNS: 192.168.1.1",
        practiceMode: "settings",
      },
      {
        id: "nat",
        title: "NAT",
        icon: "🔁",
        what: "社内で使うプライベートIPアドレスを、インターネット用のIPアドレスに変換する仕組み。",
        reality: "複数のPCが1つの回線を共有してインターネットに出られるのはNATのおかげ。",
        inGame: "ルーターの⚙設定でON/OFFできる。OFFにするとインターネットに出られなくなる。",
        example: "192.168.1.10 → NAT → Internet",
        practiceMode: "settings",
      },
    ],
  },
  {
    id: "vlan",
    title: "VLAN",
    icon: "🏷️",
    pages: [
      {
        id: "vlan_basics",
        title: "VLANとは",
        icon: "🏷️",
        what: "同じスイッチ・同じ配線につながっていても、論理的にネットワークを分離できる仕組み。",
        reality: "1台のスイッチに住民課と健康福祉課のPCが混在していても、VLANで分ければお互いに通信できなくなる。",
        inGame: "スイッチの⚙設定で各ポートにVLAN IDを割り当てる。同じVLANのポート同士だけが通信できる。",
        example: "Switch\n  ├ Port1-3: VLAN10（住民課）\n  └ Port4-6: VLAN20（健康福祉）",
        practiceMode: "settings",
      },
      {
        id: "vlan_why",
        title: "なぜVLANを使うのか",
        icon: "🏷️",
        what: "スイッチや配線を部署ごとに分けなくても、ネットワークだけを分離できるようにするため。",
        reality: "部署ごとに物理的なスイッチを用意するのはコストが高い。VLANなら1台のスイッチで済む。",
        inGame: "案件10のように「同じスイッチに複数の部署を収容しつつ分離する」場面でVLANが必要になる。",
        example: "1台のスイッチ → VLAN10（営業）/ VLAN20（開発）/ VLAN30（ゲスト）",
      },
      {
        id: "access_port",
        title: "Accessポート",
        icon: "🔌",
        what: "1つのVLANだけに所属するポート。PCなどの末端機器を接続するために使う。",
        reality: "PCを挿すポートは通常Accessポートで、そのポートのVLANにPCが所属することになる。",
        inGame: "スイッチの⚙設定でポートのモードをAccessにし、VLANを1つ選ぶ。",
        example: "Port1：Access / VLAN10（住民課）",
        practiceMode: "settings",
      },
      {
        id: "trunk_port",
        title: "Trunkポート",
        icon: "🔌",
        what: "複数のVLANを1本のケーブルで同時に通せるポート。スイッチ同士をつなぐときに使う。",
        reality: "スイッチAとスイッチBの間を全VLAN分の本数のケーブルでつなぐのは非効率なので、Trunkで1本にまとめる。",
        inGame: "Trunkに設定したポートでは、通したいVLANにチェックを入れる。設定を間違えると特定のVLANだけ通信できなくなる。",
        example: "Switch A ──Trunk（VLAN10,20,30）── Switch B",
        practiceMode: "settings",
      },
    ],
  },
  {
    id: "building",
    title: "建物とWi-Fi",
    icon: "🏢",
    pages: [
      {
        id: "wifi_attenuation",
        title: "Wi-Fiと壁",
        icon: "📶",
        what: "Wi-Fiの電波強度は、APからの距離だけでなく、途中にある壁の材質によっても弱くなる。",
        reality: "石膏ボードの壁はほとんど影響しないが、コンクリート壁は電波を大きく減衰させる。",
        inGame: "各部屋には壁の材質（石膏ボード・木製壁・ガラス・コンクリート・厚いコンクリート）が設定されており、APと機器の間にある部屋の壁を通るたびに電波強度が下がる。",
        example: "AP ))) コンクリート壁 ))) PC → 電波強度が大きく低下",
      },
      {
        id: "wifi_placement",
        title: "APの設置場所",
        icon: "📡",
        what: "Wi-Fiアクセスポイントは、電波が届かせたい場所の近く・壁の少ない位置に置く必要がある。",
        reality: "APを1台置けばオフィス全体をカバーできるとは限らない。壁の多い部屋は電波が弱くなりやすい。",
        inGame: "🔍調査や機器の「情報」画面でWi-Fi電波強度（圏外・弱・中・強）と、通過した部屋の壁を確認できる。電波が弱い場合は、APを対象の部屋に近づける・同じ部屋に設置するなどの対策が必要。",
        example: "会議室2（コンクリート壁）→ AP を会議室2の中に設置すると改善する",
        practiceMode: "diagnosing",
      },
    ],
  },
  {
    id: "troubleshooting",
    title: "トラブル対応",
    icon: "🛠️",
    pages: [
      {
        id: "check_cable",
        title: "ケーブルを確認する",
        icon: "🔌",
        what: "物理的にケーブルが抜けていないか、正しい機器につながっているかを確認する作業。",
        reality: "現場では「リンクランプ（ポートのランプ）」が点灯しているかでまず確認する。",
        inGame: "🔍調査モードで機器をタップすると、各ポートの接続先とケーブル情報を確認できる。",
        example: "PC-03のポート → 接続なし（ケーブル抜け）",
        practiceMode: "diagnosing",
      },
      {
        id: "ping",
        title: "Pingで確認する",
        icon: "📶",
        what: "相手先に信号を送り、応答が返ってくるかどうかで通信できているか調べるコマンド。",
        reality: "ping 192.168.1.1 のように打つと、応答時間や成功／失敗が表示される。",
        inGame: "🔍調査でPC・サーバーを選ぶと、Pingツールで任意のIPアドレスに送れる。",
        example: "ping 192.168.1.1 → Reply: Success",
        practiceMode: "diagnosing",
      },
      {
        id: "check_ip",
        title: "IP設定を確認する",
        icon: "🔢",
        what: "PCに正しいIPアドレス・サブネット・ゲートウェイが設定されているか確認する作業。",
        reality: "Windowsならipconfig、Macならifconfigで確認できる。",
        inGame: "⚙設定でPCを選ぶと現在の設定を確認・編集できる。DHCPなら自動取得の結果も診断で見られる。",
        example: "IP: 192.168.1.10 / Mask: 255.255.255.0",
        practiceMode: "settings",
      },
      {
        id: "check_dhcp",
        title: "DHCPを確認する",
        icon: "🤖",
        what: "IPアドレスが自動取得できているか、DHCPサーバー（ルーター）が正しく動いているか確認する作業。",
        reality: "IPアドレスが取得できない場合、ケーブルが繋がっていないかDHCPサーバーが見つからないことが多い。",
        inGame: "🔍調査の診断結果で「IPアドレスを取得できません」と出たら、物理接続とルーターのDHCP設定を確認する。",
        example: "IPアドレス：❌ DHCPサーバーが見つかりません",
        practiceMode: "diagnosing",
      },
      {
        id: "check_dns",
        title: "DNSを確認する",
        icon: "📇",
        what: "DNSサーバーの設定が正しいか確認する作業。",
        reality: "IPアドレスへの通信は成功するのに、サイト名でアクセスできない場合はDNSが疑わしい。",
        inGame: "診断結果でDNSより手前がすべて✅なのにDNSだけ❌なら、DNSサーバーのIP設定を見直す。",
        example: "Gateway: ✅ / DNS: ❌",
        practiceMode: "diagnosing",
      },
      {
        id: "check_wifi_signal",
        title: "Wi-Fi電波の弱さを確認する",
        icon: "📶",
        what: "APの電源・設定は正常なのに、距離や壁のせいで電波が弱く、通信が不安定・圏外になる障害。",
        reality: "「この部屋だけWi-Fiが弱い」という問い合わせは、たいていAPからの距離か壁の材質が原因。",
        inGame: "🔍調査の診断結果で「ケーブル長」の段階がWi-Fi圏外として失敗する。機器の「情報」画面や現場調査でも電波強度と、通過した部屋の壁を確認できる。APを近づける・移動するなどで改善する。",
        example: "ケーブル長：❌ Wi-Fi電波が圏外です（会議室2の壁を通過）",
        practiceMode: "diagnosing",
      },
      {
        id: "check_vlan",
        title: "VLANの不一致を確認する",
        icon: "🏷️",
        what: "配線もポートも正常なのに、ポートのVLAN設定が想定と違うために通信できなくなる障害。",
        reality: "「ケーブルは挿さっているのに繋がらない」という問い合わせの多くはVLAN設定ミスが原因。",
        inGame: "診断結果で物理接続・電源・ポートまで✅なのにVLANだけ❌なら、そのポートのAccess/TrunkのVLAN設定を見直す。",
        example: "ポート状態：✅ / VLAN：❌ VLAN設定が原因でRouter-01に到達できません",
        practiceMode: "diagnosing",
      },
      {
        id: "check_port",
        title: "ポート障害を確認する",
        icon: "🔌",
        what: "スイッチやルーターの特定のポートが故障し、そのポートにつながる機器だけ通信できなくなる障害。",
        reality: "ポートのランプが消えている、他のポートに挿し直すと直る、などで見分ける。",
        inGame: "⚙設定で機器を選ぶと各ポートのON/OFFを切り替えられる。OFFにしたポートを使う経路は「ポート状態」の診断で失敗する。",
        example: "Switch-01 Port03 ❌ → 経由するPCだけ通信失敗",
        practiceMode: "settings",
      },
    ],
  },
];

export function findBookPage(pageId: string): { category: BookCategory; page: BookPage } | null {
  for (const category of BOOK_CATEGORIES) {
    const page = category.pages.find((p) => p.id === pageId);
    if (page) return { category, page };
  }
  return null;
}
